### ISSUE TITLE
Other user page connection or potential page 7 

### ISSUE THREAD

**Issue by Lailah001** [iAgent-App/iAgent#32]
(create UI and connect buttons)
Should be able to see the storyboard page, buttons connect to next screen should work 
![image](https://user-images.githubusercontent.com/59979520/79817922-2a616300-834c-11ea-99fa-c84283fa9971.png)

**Comment by Daphne-CPAdmin** [comment]
Please resubmit by attaching your narrated app video in the submission notes or in the readme file. Thank you and Congratulations!
